# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-07 03:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profils', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='good',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='follower',
        ),
        migrations.AddField(
            model_name='profil',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='ist_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
